export const a = [
  {
    patientId: '7134304a-73e9-4160-9ed1-37cc3fd0124e',
    name: 'Mk Sabari Nishanth',
    age: 28,
    gender: 'male',
    phoneNumber: '9840544433',
    emailId: 'mk@g.com',
    visits: [
      {
        visitId: '391f6034-7865-400d-ac25-efc7f71f67ed',
        date: '10 Aug 2025',
        time: '12:45 pm',
        reason: 'fever',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 55, bp: 55, weight: 55, height: 55 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
  {
    patientId: '8ca6e4bc-6cf0-4c38-8944-3a9006501542',
    name: 'John Doe',
    age: 99,
    gender: 'female',
    phoneNumber: '9840544433',
    emailId: 'f.@g.com',
    visits: [
      {
        visitId: 'a0bba556-cea2-4c4f-87f1-1e33ba61d155',
        date: '10 Aug 2025',
        time: '12:46 pm',
        reason: 'dfasfdasfadsfasdf',
        doctor: 'Nishanth',
        firstVisit: 'returning',
        status: 'completed',
        vitals: { heartRate: 66, bp: 66, weight: 66, height: 66 },
        history: {
          diagnosis: 'Viral Fever',
          prescribedMedication: 'Paracetomal',
          modeOfPayment: 'Cash',
          amountPaid: '357',
          pharmacyPurchaseConfirmation: 'Yes',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: 'He is rich\\n',
        },
      },
      {
        visitId: 'fc1af787-a226-44ae-b26e-8fe0250c6c62',
        date: '10 Aug 2025',
        time: '02:15 pm',
        reason: 'fever',
        doctor: 'Nishanth',
        firstVisit: 'returning',
        status: 'completed',
        vitals: { heartRate: 66, bp: 66, weight: 66, height: 66 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
  {
    patientId: 'c1c097e6-7afb-4615-b0b1-a6a748dfb18e',
    name: 'scarlet',
    age: 50,
    gender: 'female',
    phoneNumber: '1234567890',
    emailId: 'mkdgsf@g.com',
    visits: [
      {
        visitId: '12ecf4a5-5515-4123-b35e-67ec404a1600',
        date: '10 Aug 2025',
        time: '12:46 pm',
        reason: 'afsddfsasdf',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 66, bp: 66, weight: 66, height: 66 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
      {
        visitId: 'b2c97fc0-bdc6-4c1d-8bbc-c184e9b7d739',
        date: '10 Aug 2025',
        time: '05:59 pm',
        reason: 'fever',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 55, bp: 66, weight: 66, height: 55 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
  {
    patientId: 'd88dff86-9786-418f-83f9-df575807e915',
    name: 'Madan Gowri',
    age: 4,
    gender: 'male',
    phoneNumber: '1234567890',
    emailId: 'm@g.co',
    visits: [
      {
        visitId: 'db8f05f1-a2d6-48b3-9f90-4009175f91cf',
        date: '10 Aug 2025',
        time: '12:47 pm',
        reason: 'dfssasdf',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 77, bp: 77, weight: 77, height: 77 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
  //
  {
    patientId: '7134304a-73e9-4160-9ed1-37cc3fd0124e',
    name: 'Mk Sabari Nishanth',
    age: 28,
    gender: 'male',
    phoneNumber: '9840544433',
    emailId: 'mk@g.com',
    visits: [
      {
        visitId: '391f6034-7865-400d-ac25-efc7f71f67ed',
        date: '10 Aug 2025',
        time: '12:45 pm',
        reason: 'fever',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 55, bp: 55, weight: 55, height: 55 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
  {
    patientId: '8ca6e4bc-6cf0-4c38-8944-3a9006501542',
    name: 'John Doe',
    age: 99,
    gender: 'female',
    phoneNumber: '9840544433',
    emailId: 'f.@g.com',
    visits: [
      {
        visitId: 'a0bba556-cea2-4c4f-87f1-1e33ba61d155',
        date: '10 Aug 2025',
        time: '12:46 pm',
        reason: 'dfasfdasfadsfasdf',
        doctor: 'Nishanth',
        firstVisit: 'returning',
        status: 'completed',
        vitals: { heartRate: 66, bp: 66, weight: 66, height: 66 },
        history: {
          diagnosis: 'Viral Fever',
          prescribedMedication: 'Paracetomal',
          modeOfPayment: 'Cash',
          amountPaid: '357',
          pharmacyPurchaseConfirmation: 'Yes',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: 'He is rich\\n',
        },
      },
      {
        visitId: 'fc1af787-a226-44ae-b26e-8fe0250c6c62',
        date: '10 Aug 2025',
        time: '02:15 pm',
        reason: 'fever',
        doctor: 'Nishanth',
        firstVisit: 'returning',
        status: 'completed',
        vitals: { heartRate: 66, bp: 66, weight: 66, height: 66 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
  {
    patientId: 'c1c097e6-7afb-4615-b0b1-a6a748dfb18e',
    name: 'scarlet',
    age: 50,
    gender: 'female',
    phoneNumber: '1234567890',
    emailId: 'mkdgsf@g.com',
    visits: [
      {
        visitId: '12ecf4a5-5515-4123-b35e-67ec404a1600',
        date: '10 Aug 2025',
        time: '12:46 pm',
        reason: 'afsddfsasdf',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 66, bp: 66, weight: 66, height: 66 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
      {
        visitId: 'b2c97fc0-bdc6-4c1d-8bbc-c184e9b7d739',
        date: '10 Aug 2025',
        time: '05:59 pm',
        reason: 'fever',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 55, bp: 66, weight: 66, height: 55 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
  {
    patientId: 'd88dff86-9786-418f-83f9-df575807e915',
    name: 'Madan Gowri',
    age: 4,
    gender: 'male',
    phoneNumber: '1234567890',
    emailId: 'm@g.co',
    visits: [
      {
        visitId: 'db8f05f1-a2d6-48b3-9f90-4009175f91cf',
        date: '10 Aug 2025',
        time: '12:47 pm',
        reason: 'dfssasdf',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 77, bp: 77, weight: 77, height: 77 },
        history: {
          diagnosis: '',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
];
