const a = [
  {
    patientId: '95f948ea-c148-4584-ad6e-bd311658721e',
    name: 'Mk Sabari Nishanth',
    age: 0,
    gender: 'male',
    phoneNumber: '33333',
    emailId: 'mk@g.com',
    visits: [
      {
        visitId: '599bfc78-cad7-4482-ab32-ecf4d8429614',
        date: '06 Aug 2025',
        time: '08:13 pm',
        reason: '1st',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 0, bp: 0, weight: 0, height: 0 },
        history: {
          diagnosis: '1st visit',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
];

const b = [
  {
    patientId: '95f948ea-c148-4584-ad6e-bd311658721e',
    name: 'Mk Sabari Nishanth',
    age: 0,
    gender: 'male',
    phoneNumber: '33333',
    emailId: 'mk@g.com',
    visits: [
      {
        visitId: '599bfc78-cad7-4482-ab32-ecf4d8429614',
        date: '06 Aug 2025',
        time: '08:13 pm',
        reason: '1st',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 0, bp: 0, weight: 0, height: 0 },
        history: {
          diagnosis: '1st visit',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
      {
        visitId: '1d2110e0-49d7-4f1b-b200-7bd4d724b860',
        date: '06 Aug 2025',
        time: '08:14 pm',
        reason: '2nd visit',
        doctor: 'Nishanth',
        firstVisit: 'first',
        status: 'completed',
        vitals: { heartRate: 0, bp: 0, weight: 0, height: 0 },
        history: {
          diagnosis: '2nd visit',
          prescribedMedication: '',
          modeOfPayment: '',
          amountPaid: '',
          pharmacyPurchaseConfirmation: '',
          followUpNeeded: false,
          followUpDate: '',
          additionalNotes: '',
        },
      },
    ],
  },
];
